# Shell variables
# Generated by 'wal'
wallpaper='/home/jose/Wallpapers/wallpaper5.png'

# Special
background='#191918'
foreground='#e9e1cf'
cursor='#e9e1cf'

# Colors
color0='#191918'
color1='#A89071'
color2='#B46C87'
color3='#568C89'
color4='#A0A390'
color5='#D29E98'
color6='#B7C5A6'
color7='#e9e1cf'
color8='#a39d90'
color9='#A89071'
color10='#B46C87'
color11='#568C89'
color12='#A0A390'
color13='#D29E98'
color14='#B7C5A6'
color15='#e9e1cf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
