# Shell variables
# Generated by 'wal'
wallpaper='/home/jose/Wallpapers/wallpaper11.png'

# Special
background='#0E0B20'
foreground='#c5e5ec'
cursor='#c5e5ec'

# Colors
color0='#0E0B20'
color1='#AA09E4'
color2='#F10BD7'
color3='#F86FEE'
color4='#D698EC'
color5='#F991F6'
color6='#F5AEFA'
color7='#c5e5ec'
color8='#89a0a5'
color9='#AA09E4'
color10='#F10BD7'
color11='#F86FEE'
color12='#D698EC'
color13='#F991F6'
color14='#F5AEFA'
color15='#c5e5ec'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
